language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
deploy:
  provider: releases
  api_key:
    secure: ZeBPvxqrsLP/rQ61iS7xAAxRWb3nK1rJnJB8J8Y7ALarRYj16b03JdQyh01eeHYQ1FVdBVQE+SMktPWCu+6xlr4IiaU2fGxH+OX4SJoi3lquHpT64GZLkL2m+TxPbH3RHv9eHM1aBOw0qvGHzZL/326GDeiO9tt6CLBMg7Vp29c=
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup:  true
  on:
	  tags: true
	  all_branches: true
android:
  components:
  - build-tools-22.0.1
before_install:
- chmod +x gradlew
script: ./gradlew assembleDebug
